### ISSUE TITLE
Updating for Socket.IO 1.0

### ISSUE THREAD

**Issue by shijuvar** [azure-contrib/socket.io-servicebus#73] opened 2014-05-30 05:59 UTC
Socket.IO 1.0 has released - http://socket.io/blog/introducing-socket-io-1-0/. Has any plan for update the library for working with Socket.IO 1.0.?

**Comment by ghost** [comment] 2014-09-15 06:32
We are egerly waiting for this thing to work. We are getting the error (screenshot attached)

Please do update some work around for the same in msahoo@newclassrooms.org

![image](https://cloud.githubusercontent.com/assets/6048590/4267741/f5c81856-3ca1-11e4-9c09-013c23bdaaab.jpg)

**Comment by glennblock** [comment] 2015-04-01 01:08
Closing as Duplicate of #75

**Closed as completed** 2015-04-01 01:08 UTC
